### ISSUE TITLE
'Module' object has no attribute 'ProbeCommandHelper'

### ISSUE THREAD

**Issue by hfustercabre** [frap129/qidi_auto_z_offset#4]
I tried to install it in my Q1 Pro with stock firmware and I recibe the following error:

```
Unhandled exception during connect
Traceback (most recent call last):
  File "/home/mks/klipper/klippy/klippy.py", line 193, in _connect
    self._read_config()
  File "/home/mks/klipper/klippy/klippy.py", line 159, in _read_config
    self.load_object(config, section_config.get_name(), None)
  File "/home/mks/klipper/klippy/klippy.py", line 134, in load_object
    mod = importlib.import_module('extras.' + module_name)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/home/mks/klipper/klippy/extras/auto_z_offset.py", line 14, in <module>
    class AutoZOffsetCommandHelper(probe.ProbeCommandHelper):
AttributeError: 'module' object has no attribute 'ProbeCommandHelper'
webhooks client 281473506591808: New connection
webhooks client 281473506591808: Client info {'program': 'Moonraker', 'version': 'v0.7.1-609-gbdd0222-dirty'}
Internal error during connect: 'module' object has no attribute 'ProbeCommandHelper'
Once the underlying issue is corrected, use the "RESTART"
command to reload the config and restart the host software.
Printer is halted
```

My configuration is the following:

```
[probe]
pin: !gpio21
x_offset: 17.6
y_offset: 4.4
z_offset: 0.0
speed:10
samples: 3
samples_result: average
sample_retract_dist: 4.0
samples_tolerance: 0.05
samples_tolerance_retries: 5

[auto_z_offset]
pin: U_1:PC1
z_offset: -0.1
speed: 10
probe_accel: 50
samples: 3
samples_result: average
samples_tolerance: 0.05
samples_tolerance_retries: 5
prepare_gcode:
SET_PIN PIN=ctlyd VALUE=0
    G91
    {% set i = 4 %}
    {% for iteration in range(i|int) %}
        G1 Z1 F900
        G1 Z-1 F900
    {% endfor %}
    G90
    SET_PIN PIN=ctlyd VALUE=1

``` 
The pin for the bed_sensor was already on use so I changed it in the gcode.

Is it possible that the script only works with OpenQ1?

Thanks!

**Comment by frap129** [comment]
This will not work with QIDI's 2 year old version of klipper
